name: SampleProject #change this
targets:
  SampleProject: #change this
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 16.0
    info:
      path: Plists/SampleProject/Info.plist #change this
      properties:
        CFBundleIdentifier: dev.cctplus.SampleProject #change this
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown]
    settings: 
      base:
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      configs:
        debug:
          DEBUG_MODE: YES
        release:
          DEBUG_MODE: NO
    postCompileScripts:
      - script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/App
  TestTargetName: #change this
    platform: iOS
    type: bundle.unit-test
    info:
      path: Plists/Tests/Info.plist #change this
      properties:
        CFBundleIdentifier: dev.cctplus.SampleProjectTests #change this
    sources:
      - path: Sources/Tests
    dependencies:
      - target: SampleProject #change this to the app target name
    scheme:
      testTargets:
        - TestTargetName
      gatherCoverageData: true